
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 30 22:20:26 CST 2019
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 4;
  public static final int alla = 2;
  public static final int EOF = 0;
  public static final int chaR = 7;
  public static final int booL = 8;
  public static final int error = 1;
  public static final int clla = 3;
  public static final int inT = 6;
  public static final int pyc = 5;
}

